version: '3.3'

volumes:
  mongodb_data:
    driver: local

services:
  mongodb:
    image: 'mongodb/mongodb-community-server:7.0.0-ubi8'
    container_name: mongodb
    ports:
      - '27017:27017'
    volumes:
      - 'mongodb_data:/data/db'
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass 

